### PR TITLE
Fixing intermittent Kafka tx-fn arg doc replacement test, #1256

### LINKED ISSUE #1256: Intermittent test - `api-test/test-tx-fn-replacing-arg-docs-866`
Caused by a race condition. The Kafka doc-store is asynchronous - docs have to go on the doc-topic, then (later) get indexed into the local document store. #1470 and #1493 make this better for normal docs, by having `fetch-docs` wait til the document's indexed locally. With tx-fn arg docs, though, the doc is already indexed locally, so `fetch-docs` immediately returns the old document. 

Lucene (as of #1535) will assume that the tx-fn doc has been replaced as soon as the transaction's committed.

---

See https://app.circleci.com/pipelines/github/juxt/crux/1597/workflows/7f618b9e-0173-4563-aece-ba93d29bf8fa/jobs/6404

```
FAIL in (test-tx-fn-replacing-arg-docs-866) (api_test.clj:424)
:local-kafka-transit replaces args doc with resulting ops
expected: (= #:crux.db.fn{:tx-events [[:crux.tx/put (c/new-id :ivan) (c/new-id {:crux.db/id :ivan, :name "Ivan"})]]} (-> (db/fetch-docs (:document-store *server-api*) #{arg-doc-id}) (get arg-doc-id) (dissoc :crux.db/id)))
  actual: (not (= #:crux.db.fn{:tx-events [[:crux.tx/put #crux/id "a15f8b81a160b4eebe5c84e9e3b65c87b9b2f18e" #crux/id "0d0a27eff76f1b60e77e342e4eeeeb6470696351"]]} #:crux.db.fn{:args ({:name "Ivan"})}))
10:25:12.598 [main] WARN  crux.query - `full-results?` is deprecated and will be removed in a future Crux release.  Use `(eql/project ?e [*])` instead - see https://opencrux.com/reference/queries.html#eql-projection
```

Also related to the following intermittent test:
```
FAIL in (test-tx-log) (api_test.clj:275)
:local-kafka tx-log tx fns return with-ops? correctly
expected: (= [:crux.tx/fn (c/new-id :increment-age-2) #:crux.api{:tx-ops [[:crux.tx/fn (c/new-id :increment-age) #:crux.api{:tx-ops [[:crux.tx/put {:crux.db/id :jack, :age 22}]]}]]}] (last tx-ops))
  actual: (not (= [:crux.tx/fn #crux/id "7b3961b3ed263aff1adde3e92a29eeb550380d1e" #:crux.api{:tx-ops [[:crux.tx/fn #crux/id "46995cbc65f1a439b86a848bb3506bce65e8f6ca" #:crux.api{:tx-ops [[:crux.tx/put {:crux.db/id :jack, :age 22}]]}]]}] [:crux.tx/fn #crux/id "7b3961b3ed263aff1adde3e92a29eeb550380d1e" {:crux.db.fn/args (:jack), :crux.api/tx-ops ()}]))
```

### PR DESCRIPTION
**Pull request by jarohen**
Fast-tracking tx-fn doc replacements straight to the Kafka local doc-store, fixes #1256

### CODE REVIEW

File: crux-kafka/src/crux/kafka.clj [hunk 1]
```diff
@@ -265,7 +265,14 @@
 
   db/DocumentStore
   (submit-docs [this id-and-docs]
-    (submit-docs id-and-docs this))
+    (submit-docs id-and-docs this)
+
+    ;; for #1256 - let's fast-track tx-fn doc replacements straight into the local doc-store
```
Comment (jonpither) [inline crux-kafka/src/crux/kafka.clj]: You kind of push the reader towards checking out the issue #1256 for explanation of this code path, but there's no actual description on that issue as to what the problem is, just a broken test.

Comment (jarohen) [reply crux-kafka/src/crux/kafka.clj]: Good shout - reckon it's best to update the issue, the comment, or both?

Comment (jarohen) [reply crux-kafka/src/crux/kafka.clj]: Gone for both :smile:
