### PR TITLE
Fix: postgres errors in `handle-msg` were being responded as unexpected exceptions

### LINKED ISSUE #4628: Do not log "query cancelled" as an ERROR, and possibly recategorize
It is currently logged at an ERROR level:

XTDB logs
```
12:50:10.315 [pgwire-connection--pool-1-thread-6] ERROR xtdb.pgwire - Uncaught exception processing message
xtdb.error.Fault: query cancelled during execution
	at xtdb.error$fault.invokeStatic(error.clj:90)
	at xtdb.error$fault.invoke(error.clj:82)
	at xtdb.error$eval1978$fn__1979.invoke(error.clj:204)
	at xtdb.error$eval1897$fn__1898$G__1888__1905.invoke(error.clj:14)
	at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1399)
...
```

It also seems to be sending an incorrect error code to the client, and categorized as `:fault`. From a PostgresJS client:
```
 PostgresError: query cancelled during execution
	{
	  severity: 'ERROR',
	  severity_local: 'ERROR',
	  code: 'XX000',
	  detail: '["~#xt/error",["~:fault","~:xtdb.error/unknown","query cancelled during execution",["^ "]]]',
	  query: 'SELECT pg_sleep(5.0)',
	  parameters: [],
	  args: [],
	  types: []
	}
```

Compare to what is received from standard PostgreSQL:
```
	PostgresError: canceling statement due to user request
	{
	  severity_local: 'ERROR',
	  severity: 'ERROR',
	  code: '57014',
	  file: 'postgres.c',
	  line: '3425',
	  routine: 'ProcessInterrupts',
	  query: 'SELECT pg_sleep(5.0)',
	  parameters: [],
	  args: [],
	  types: []
	}
```

Note: Although we are requesting to change the XT category, the Postgres `severity` should stay as "ERROR" for compatibility.

### PR DESCRIPTION
**Pull request by egg-juxt**
There was a redundant `wrap-anomaly` in `pg-wire/handle-msg`, which made the existing error-handling (`send-ex`) not work correctly.

I have made sure that existing ex-infos with a pg error-code and unexpected exceptions are also conveyed properly to the client.

### CODE REVIEW

File: core/src/main/clojure/xtdb/pgwire.clj [hunk 1]
```diff
@@ -244,19 +244,23 @@
 
 (defn send-ex [{:keys [conn-state] :as conn}, ^Throwable ex]
   (let [ex-msg (ex-message ex)
-        {::keys [severity error-code routine]} (if (::error-code (ex-data ex))
-                                                 (ex-data ex)
-                                                 (ex->pgw-err (err/->anomaly ex {})))
+
+        {::keys [severity error-code routine] :keys [detail]}
```
Comment (jarohen) [inline core/src/main/clojure/xtdb/pgwire.clj]: nit: commas in one-line maps - `{::keys [...], :keys [...]}`

File: core/src/main/clojure/xtdb/pgwire.clj [hunk 2]
```diff
@@ -244,19 +244,23 @@
...
+        (if (::error-code (ex-data ex))
+          (ex-data ex)
+          (let [ex (err/->anomaly ex {})]
+            (-> (ex->pgw-err ex)
+              (assoc :detail (case (get-in @conn-state [:session :parameters "fallback_output_format"])
```
Comment (jarohen) [inline core/src/main/clojure/xtdb/pgwire.clj]: nit: alignment

File: core/src/main/clojure/xtdb/pgwire.clj [hunk 3]
```diff
@@ -1413,10 +1417,9 @@
   (try
     (log/trace "Read client msg" {:cid cid, :msg msg})
 
-    (err/wrap-anomaly {}
-      (if (and (:skip-until-sync? @conn-state) (not= :msg-sync msg-name))
-        (log/trace "Skipping msg until next sync due to error in extended protocol" {:cid cid, :msg msg})
-        (handle-msg* conn msg)))
+    (if (and (:skip-until-sync? @conn-state) (not= :msg-sync msg-name))
```
Comment (jarohen) [inline core/src/main/clojure/xtdb/pgwire.clj:1551]: the Interrupted case below here seems to rely on this being wrapped in wrap-anomaly.

**Review by jarohen — APPROVED** [review]

File: core/src/main/clojure/xtdb/pgwire.clj (hunk 3 above)
Comment (egg-juxt) [reply core/src/main/clojure/xtdb/pgwire.clj:1551]: I am adding the catch for InterruptedException, following the same pattern as in other places in this file.

However, I'm not understanding the purpose of wrapping exceptions into Anomaly exceptions. What is the goal we are pursuing?
