### PR TITLE
Ensure pgwire portals are closed as per the spec, fixes #4233. Also return error if portal already exists

### LINKED ISSUE #4233: Memory leak when passing a parameter in a `READ ONLY` transaction
<details><summary>Setup</summary>

```bash
❯ node --version
v22.11.0
```

`package.json`:
```json
{
  "name": "js-postgres-setup",
  "packageManager": "yarn@3.5.0",
  "type": "module",
  "dependencies": {
    "postgres": "^3.4.5"
  }
}
```

</details>

With the following code:
```js
import postgres from "postgres";

const sql = postgres({
  host: "localhost",
  port: 5432,
  username: "xtdb",
  password: "xtdb",
  database: "xtdb",
  fetch_types: false,
  onnotice: (_) => {},
});

// Bug in driver
await sql`SELECT 1`;

const sql2 = await sql.reserve();

await sql2`BEGIN READ ONLY`;
console.log(await sql2`SELECT ${1}`);
await sql2`COMMIT`;
sql2.release();

sql.end();
```

Running vs: `docker run -it --pull=always -e XTDB_LOGGING_LEVEL=debug -p 5432:5432 ghcr.io/xtdb/xtdb:2.0.0-beta6`

I get the following logs:

<details><summary>Logs</summary>

```
Starting XTDB 2.x @ 2.0.0-beta6 @ df55068 ...
13:50:47 | INFO  xtdb.metrics | tagging all metrics with node-id: a20a7cb6
13:50:48 | INFO  xtdb.pgwire | Server started on port: 5432
13:50:48 | INFO  xtdb.healthz | Healthz server started on port: 8080
13:50:48 | INFO  xtdb.server | HTTP server started on port: 3000
13:50:48 | INFO  xtdb.cli | Node started
13:51:04 | DEBUG xtdb.pgwire | Interpreting SQL:  SELECT 1
13:51:04 | DEBUG xtdb.pgwire | Interpreting SQL:  BEGIN READ ONLY
13:51:04 | DEBUG xtdb.pgwire | Interpreting SQL:  SELECT $1
13:51:04 | DEBUG xtdb.pgwire | Interpreting SQL:  COMMIT
13:51:04 | ERROR o.apache.arrow.memory.BaseAllocator | Memory was leaked by query. Memory leaked: (36866)
Allocator(pg-conn-1) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)

^C13:51:07 | INFO  xtdb.server | HTTP server stopped.
13:51:07 | INFO  xtdb.healthz | Healthz server stopped.
13:51:07 | ERROR o.apache.arrow.memory.BaseAllocator | Memory was leaked by query. Memory leaked: (36866)
Outstanding child allocators : 
  Allocator(pg-conn-1) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)
Allocator(pgwire) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)

{:clojure.main/message
 "Execution error (IllegalStateException) at org.apache.arrow.memory.BaseAllocator/close (BaseAllocator.java:504).\nMemory was leaked by query. Memory leaked: (36866)\nOutstanding child allocators : \n  Allocator(pg-conn-1) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)\nAllocator(pgwire) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)\n\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.IllegalStateException,
  :clojure.error/line 504,
  :clojure.error/cause
  "Memory was leaked by query. Memory leaked: (36866)\nOutstanding child allocators : \n  Allocator(pg-conn-1) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)\nAllocator(pgwire) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)\n",
  :clojure.error/symbol org.apache.arrow.memory.BaseAllocator/close,
  :clojure.error/source "BaseAllocator.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.ExceptionInfo,
    :message "Error on key :xtdb.pgwire/server when running system",
    :data
    {:reason :integrant.core/run-threw-exception,
     :system
     {:xtdb/log
      #object[xtdb.api.log.LocalLog 0x412728d5 "xtdb.api.log.LocalLog@412728d5"],
      :xtdb/modules
      {"xtdb.http-server"
       #object[xtdb.server$open_server$reify__38163 0x27361751 "xtdb.server$open_server$reify__38163@27361751"]},
      :xtdb.metadata/metadata-manager
      #object[xtdb.metadata.MetadataManager 0x4a8a2902 "xtdb.metadata.MetadataManager@4a8a2902"],
      :xtdb/trie-catalog {:!table-tries {}},
      :xtdb.indexer/live-index
      #object[xtdb.indexer.live_index.LiveIndex 0x637b4abf "xtdb.indexer.live_index.LiveIndex@637b4abf"],
      :xtdb.operator.scan/scan-emitter
      #object[xtdb.operator.scan$eval25253$fn$reify__25258 0x3f16b11e "xtdb.operator.scan$eval25253$fn$reify__25258@3f16b11e"],
      :xtdb.log/processor
      #object[xtdb.indexer.LogProcessor 0x114536bb "xtdb.indexer.LogProcessor@114536bb"],
      :xtdb/authn
      {:rules
       [{:method #xt.authn/method :trust,
         :user nil,
         :remote-addr nil}]},
      :xtdb.query/query-source
      #object[xtdb.query$eval29516$fn$reify__29520 0x55f7a963 "xtdb.query$eval29516$fn$reify__29520@55f7a963"],
      :xtdb/healthz
      #object[xtdb.healthz$eval34419$fn$reify__34423 0x26645c89 "xtdb.healthz$eval34419$fn$reify__34423@26645c89"],
      :xtdb/indexer
      {:allocator
       #object[org.apache.arrow.memory.ChildAllocator 0x7061f42a "Allocator(indexer) 0/0/0/9223372036854775807 (res/actual/peak/limit)\n"],
       :node-id "a20a7cb6",
       :buffer-pool
       #object[xtdb.buffer_pool.LocalBufferPool 0x256bcf8c "xtdb.buffer_pool.LocalBufferPool@256bcf8c"],
       :metadata-mgr
       #object[xtdb.metadata.MetadataManager 0x4a8a2902 "xtdb.metadata.MetadataManager@4a8a2902"],
       :q-src
       #object[xtdb.query$eval29516$fn$reify__29520 0x55f7a963 "xtdb.query$eval29516$fn$reify__29520@55f7a963"],
       :live-idx
       #object[xtdb.indexer.live_index.LiveIndex 0x637b4abf "xtdb.indexer.live_index.LiveIndex@637b4abf"],
       :tx-timer
       #object[io.micrometer.core.instrument.composite.CompositeTimer 0x76aa7736 "io.micrometer.core.instrument.composite.CompositeTimer@81e2d839"]},
      :xtdb.pgwire/server
      {:read-write
       {:allocator
        #object[org.apache.arrow.memory.ChildAllocator 0x792318c8 "Allocator(pgwire) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)\n"],
        :port 5432,
        :read-only? false,
        :accept-socket
        #object[java.net.ServerSocket 0x2f2e9b85 "ServerSocket[addr=0.0.0.0/0.0.0.0,localport=5432]"],
        :accept-thread
        #object[java.lang.VirtualThread 0x66863b71 "VirtualThread[#33,pgwire-server-accept-5432]/terminated"],
        :thread-pool
        #object[java.util.concurrent.ThreadPoolExecutor 0x71dd138f "java.util.concurrent.ThreadPoolExecutor@71dd138f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]"],
        :!closing? #<Atom@7ffca9b2: true>,
        :server-state
        #<Atom@430c979c: 
          {:clock
           #object[java.time.Clock$SystemClock 0x2e1940b "SystemClock[Etc/UTC]"],
           :drain-wait 5000,
           :parameters
           {"IntervalStyle" "ISO_8601",
            "client_encoding" "UTF8",
            "TimeZone" "Etc/UTC",
            "integer_datetimes" "on",
            "standard_conforming_strings" "on",
            "search_path" "public",
            "server_encoding" "UTF8",
            "server_version" "16",
            "DateStyle" "ISO"},
           :next-cid 1,
           :connections {}}>,
        :authn-rules nil,
        :!tmp-nodes nil,
        :ssl-ctx nil,
        :authn
        {:rules
         [{:method #xt.authn/method :trust,
           :user nil,
           :remote-addr nil}]},
        :query-error-counter
        #object[io.micrometer.core.instrument.composite.CompositeCounter 0x4ca9cb57 "io.micrometer.core.instrument.composite.CompositeCounter@72878bf9"],
        :->node
        #object[xtdb.pgwire$serve$fn__31363 0x64bef72 "xtdb.pgwire$serve$fn__31363@64bef72"]},
       :read-only nil},
      :xtdb/node #<XtdbNode>,
      :xtdb/config {:node-id "a20a7cb6", :default-tz #xt/zone "Z"},
      :xtdb.metrics/registry
      #object[io.micrometer.core.instrument.composite.CompositeMeterRegistry 0x3e60c10f "io.micrometer.core.instrument.composite.CompositeMeterRegistry@3e60c10f"],
      :xtdb/compactor
      #object[xtdb.compactor.Compactor$Companion$open$1 0x3519de7e "xtdb.compactor.Compactor$Companion$open$1@3519de7e"],
      :xtdb/buffer-pool
      #object[xtdb.buffer_pool.LocalBufferPool 0x256bcf8c "xtdb.buffer_pool.LocalBufferPool@256bcf8c"],
      :xtdb/allocator
      #object[org.apache.arrow.memory.RootAllocator 0x36af62fb "Allocator(ROOT) 0/272010/272034/9223372036854775807 (res/actual/peak/limit)\n"]},
     :completed-keys (:xtdb/modules :xtdb/healthz),
     :remaining-keys
     (:xtdb/node
      :xtdb/authn
      :xtdb.log/processor
      :xtdb/indexer
      :xtdb.query/query-source
      :xtdb.operator.scan/scan-emitter
      :xtdb.indexer/live-index
      :xtdb/compactor
      :xtdb/trie-catalog
      :xtdb/log
      :xtdb.metadata/metadata-manager
      :xtdb/buffer-pool
      :xtdb/allocator
      :xtdb.metrics/registry
      :xtdb/config),
     :function
     #object[clojure.lang.MultiFn 0x797fb51 "clojure.lang.MultiFn@797fb51"],
     :key :xtdb.pgwire/server,
     :value
     {:read-write
      {:allocator
       #object[org.apache.arrow.memory.ChildAllocator 0x792318c8 "Allocator(pgwire) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)\n"],
       :port 5432,
       :read-only? false,
       :accept-socket
       #object[java.net.ServerSocket 0x2f2e9b85 "ServerSocket[addr=0.0.0.0/0.0.0.0,localport=5432]"],
       :accept-thread
       #object[java.lang.VirtualThread 0x66863b71 "VirtualThread[#33,pgwire-server-accept-5432]/terminated"],
       :thread-pool
       #object[java.util.concurrent.ThreadPoolExecutor 0x71dd138f "java.util.concurrent.ThreadPoolExecutor@71dd138f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]"],
       :!closing? #<Atom@7ffca9b2: true>,
       :server-state
       #<Atom@430c979c: 
         {:clock
          #object[java.time.Clock$SystemClock 0x2e1940b "SystemClock[Etc/UTC]"],
          :drain-wait 5000,
          :parameters
          {"IntervalStyle" "ISO_8601",
           "client_encoding" "UTF8",
           "TimeZone" "Etc/UTC",
           "integer_datetimes" "on",
           "standard_conforming_strings" "on",
           "search_path" "public",
           "server_encoding" "UTF8",
           "server_version" "16",
           "DateStyle" "ISO"},
          :next-cid 1,
          :connections {}}>,
       :authn-rules nil,
       :!tmp-nodes nil,
       :ssl-ctx nil,
       :authn
       {:rules
        [{:method #xt.authn/method :trust,
          :user nil,
          :remote-addr nil}]},
       :query-error-counter
       #object[io.micrometer.core.instrument.composite.CompositeCounter 0x4ca9cb57 "io.micrometer.core.instrument.composite.CompositeCounter@72878bf9"],
       :->node
       #object[xtdb.pgwire$serve$fn__31363 0x64bef72 "xtdb.pgwire$serve$fn__31363@64bef72"]},
      :read-only nil}},
    :at [integrant.core$run_exception invokeStatic "core.cljc" 357]}
   {:type java.lang.IllegalStateException,
    :message
    "Memory was leaked by query. Memory leaked: (36866)\nOutstanding child allocators : \n  Allocator(pg-conn-1) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)\nAllocator(pgwire) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)\n",
    :at
    [org.apache.arrow.memory.BaseAllocator
     close
     "BaseAllocator.java"
     504]}],
  :trace
  [[org.apache.arrow.memory.BaseAllocator
    close
    "BaseAllocator.java"
    504]
   [xtdb.util$close invokeStatic "util.clj" 51]
   [xtdb.util$close invoke "util.clj" 34]
   [xtdb.pgwire.Server close "pgwire.clj" 102]
   [xtdb.util$close invokeStatic "util.clj" 51]
   [xtdb.util$close invoke "util.clj" 34]
   [xtdb.util$close$close_all__5513$fn__5516 invoke "util.clj" 39]
   [clojure.core.protocols$iterator_reduce_BANG_
    invokeStatic
    "protocols.clj"
    42]
   [clojure.core.protocols$iter_reduce invokeStatic "protocols.clj" 52]
   [clojure.core.protocols$fn__8256 invokeStatic "protocols.clj" 74]
   [clojure.core.protocols$fn__8256 invoke "protocols.clj" 74]
   [clojure.core.protocols$fn__8203$G__8198__8216
    invoke
    "protocols.clj"
    13]
   [clojure.core$reduce invokeStatic "core.clj" 6965]
   [clojure.core$reduce invoke "core.clj" 6947]
   [xtdb.util$close$close_all__5513 invoke "util.clj" 37]
   [xtdb.util$close invokeStatic "util.clj" 52]
   [xtdb.util$close invoke "util.clj" 34]
   [xtdb.pgwire$eval31399$fn__31400 invoke "pgwire.clj" 2076]
   [clojure.lang.MultiFn invoke "MultiFn.java" 234]
   [integrant.core$try_run_action invokeStatic "core.cljc" 369]
   [integrant.core$try_run_action invoke "core.cljc" 367]
   [integrant.core$run_loop invokeStatic "core.cljc" 377]
   [integrant.core$run_loop invoke "core.cljc" 373]
   [integrant.core$reverse_run_BANG_ invokeStatic "core.cljc" 397]
   [integrant.core$reverse_run_BANG_ invoke "core.cljc" 391]
   [integrant.core$halt_BANG_ invokeStatic "core.cljc" 683]
   [integrant.core$halt_BANG_ invoke "core.cljc" 677]
   [integrant.core$halt_BANG_ invokeStatic "core.cljc" 680]
   [integrant.core$halt_BANG_ invoke "core.cljc" 677]
   [xtdb.node.impl$open_node$fn__30200 invoke "impl.clj" 279]
   [xtdb.node.impl.Node close "impl.clj" 190]
   [xtdb.util$close invokeStatic "util.clj" 51]
   [xtdb.util$close invoke "util.clj" 34]
   [xtdb.cli$start_node_from_command_line invokeStatic "cli.clj" 104]
   [xtdb.cli$start_node_from_command_line invoke "cli.clj" 91]
   [clojure.lang.Var invoke "Var.java" 386]
   [xtdb.main$_main invokeStatic "main.clj" 17]
   [xtdb.main$_main doInvoke "main.clj" 5]
   [clojure.lang.RestFn applyTo "RestFn.java" 140]
   [clojure.lang.Var applyTo "Var.java" 707]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.main$main_opt invokeStatic "main.clj" 515]
   [clojure.main$main_opt invoke "main.clj" 511]
   [clojure.main$main invokeStatic "main.clj" 665]
   [clojure.main$main doInvoke "main.clj" 617]
   [clojure.lang.RestFn applyTo "RestFn.java" 140]
   [clojure.lang.Var applyTo "Var.java" 707]
   [clojure.main main "main.java" 40]],
  :cause
  "Memory was leaked by query. Memory leaked: (36866)\nOutstanding child allocators : \n  Allocator(pg-conn-1) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)\nAllocator(pgwire) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)\n"}}

Execution error (IllegalStateException) at org.apache.arrow.memory.BaseAllocator/close (BaseAllocator.java:504).
Memory was leaked by query. Memory leaked: (36866)
Outstanding child allocators : 
  Allocator(pg-conn-1) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)
Allocator(pgwire) 0/36866/36866/9223372036854775807 (res/actual/peak/limit)


13:51:17 | WARN  xtdb.cli | could not stop node cleanly after 10000 ms, forcing exit
```

</details>

### PR DESCRIPTION
**Pull request by mbutlerw**

### CODE REVIEW

File: core/src/main/clojure/xtdb/pgwire.clj [hunk 1]
```diff
@@ -1706,14 +1712,26 @@
 
         stmt))))
 
+(defn unamed-portal? [portal-name]
```
Comment (jarohen) [inline core/src/main/clojure/xtdb/pgwire.clj:1715]: nit: `unnamed`

File: lang/js/test/test.js [hunk 2]
```diff
@@ -150,3 +150,26 @@ describe("connects to XT", function() {
...
+    await sql2`BEGIN TRANSACTION READ ONLY`;
+    await sql2`SELECT ${2}`;
+    await sql2`COMMIT`;
+    // lib uses extended flow by default, commit therefore was being bound as unamed portal
+    // ref to previous portal was being lost and therefore never closed
+    sql2.release();
+    sql.end();
+  })
+
+  it("implcitly closes unamed portal at start of simple query", async () => {
```
Comment (jarohen) [inline lang/js/test/test.js:167]: implicitly

**Review by jarohen — APPROVED** [review]
thanks @mbutlerw :pray:
