### PR TITLE
BigDecimal and java.time classes as value types

### LINKED ISSUE #1236: Unusual '>' predicate behaviour when value is BigDecimal.
Hi Team,

We are upgrading to the latest from an old version (a big jump too) and noticed some changed behaviours around the '>' predicate within queries.  The following test passes for the old version and fails hard for the new version.

Old CRUX Version: [juxt/crux-core "20.03-1.7.1-alpha"]
New CRUX Version: [juxt/crux-core "20.09-1.12.1-beta"]

**Workaround**: Use 'clojure.core/>' instead of '>' in the query clause.

To reproduce:
```clojure
(def node (atom nil))

(defn db-setup [f]
  ;; For old Crux Version, use the following node creation.
  ;; (reset! node (crux/start-node {:crux.node/topology :crux.standalone/topology}))
  (reset! node (crux.api/start-node {}))
  (f)
  (.close @node)
  (reset! node nil))

(use-fixtures :each db-setup)

(deftest crux-investigation-test
  (let [data [{:crux.db/id :id-1 :value 0M}
              {:crux.db/id :id-2 :value 0.0M}
              {:crux.db/id :id-3 :value 0.000M}
              {:crux.db/id :id-4 :value BigDecimal/ZERO}
              {:crux.db/id :id-5 :value (BigDecimal. "0")}
              {:crux.db/id :id-6 :value (BigDecimal. "0.0")}
              {:crux.db/id :id-7 :value (BigDecimal. "0.000")}
              {:crux.db/id :id-8 :value (BigDecimal. "1")}
              {:crux.db/id :id-9 :value (BigDecimal. "0.1")}
              {:crux.db/id :id-10 :value (BigDecimal. "0.001")}]
        tx (mapv #(vector :crux.tx/put %) data)
        tx-rpt (crux.api/submit-tx @node tx)]
    (crux.api/await-tx @node tx-rpt)

    (testing "verify that '>' predicate for BigDecimal does not work as expected"
      (doseq [[threshold label] [[0M "0M"]
                                 [0.0M "0.0M"]
                                 [0.000M  "0.000M"]
                                 [BigDecimal/ZERO "BigDecimal/ZERO"]
                                 [(BigDecimal. "0") "BigDecimal('0')"]
                                 [(BigDecimal. "0.0") "BigDecimal('0.0')"]
                                 [(BigDecimal. "0.000") "BigDecimal('0.000')"]]]
        (is (= (->> (filter #(> (:value %) threshold) data)
                    (mapv :crux.db/id)
                    set)
               #{:id-8 :id-9 :id-10})
            (str "'filter' and '>' provide the expected matched entities for threshold: " label))

        (is (= (->> (crux.api/q (crux.api/db @node)
                                {:find '[?e]
                                 :where '[[?e :value ?v]
                                          [(> ?v ?threshold)]]
                                 :args [{'?threshold threshold}]})
                    (mapv first)
                    set)
               #{:id-8 :id-9 :id-10})
            (str "Query with '>' predicate yields different results for threshold: " label))

        (is (= (->> (crux.api/q (crux.api/db @node)
                                {:find '[?e]
                                 :where '[[?e :value ?v]
                                          [(clojure.core/> ?v ?threshold)]]
                                 :args [{'?threshold threshold}]})
                    (mapv first)
                    set)
               #{:id-8 :id-9 :id-10})

            (str "Query with 'clojure.core/>' returns the expected results for threshold: " label))))

    (testing "verify that '>' works as expected for BigDecimal"
      (is (not (> 0M 0M)))
      (is (not (> 0.0M 0M)))
      (is (not (> BigDecimal/ZERO 0M)))
      (is (not (> (BigDecimal. "0") 0M)))
      (is (not (> (BigDecimal. "0.0") 0M)))
      (is (not (> (BigDecimal. "0.000") 0M)))

      (is (not (> 0M 0.0M)))
      (is (not (> 0.0M 0.0M)))
      (is (not (> BigDecimal/ZERO 0.0M)))
      (is (not (> (BigDecimal. "0") 0.0M)))
      (is (not (> (BigDecimal. "0.0") 0.0M)))
      (is (not (> (BigDecimal. "0.000") 0.0M)))

      (is (not (> 0M BigDecimal/ZERO)))
      (is (not (> 0.0M BigDecimal/ZERO)))
      (is (not (> BigDecimal/ZERO BigDecimal/ZERO)))
      (is (not (> (BigDecimal. "0") BigDecimal/ZERO)))
      (is (not (> (BigDecimal. "0.0") BigDecimal/ZERO)))
      (is (not (> (BigDecimal. "0.000") BigDecimal/ZERO)))

      (is (not (> 0M (BigDecimal. "0"))))
      (is (not (> 0.0M (BigDecimal. "0"))))
      (is (not (> BigDecimal/ZERO (BigDecimal. "0"))))
      (is (not (> (BigDecimal. "0") (BigDecimal. "0"))))
      (is (not (> (BigDecimal. "0.0") (BigDecimal. "0"))))
      (is (not (> (BigDecimal. "0.000") (BigDecimal. "0"))))

      (is (not (> 0M (BigDecimal. "0.0"))))
      (is (not (> 0.0M (BigDecimal. "0.0"))))
      (is (not (> BigDecimal/ZERO (BigDecimal. "0.0"))))
      (is (not (> (BigDecimal. "0") (BigDecimal. "0.0"))))
      (is (not (> (BigDecimal. "0.0") (BigDecimal. "0.0"))))
      (is (not (> (BigDecimal. "0.000") (BigDecimal. "0.0"))))

      (is (not (> 0M (BigDecimal. "0.000"))))
      (is (not (> 0.0M (BigDecimal. "0.000"))))
      (is (not (> BigDecimal/ZERO (BigDecimal. "0.000"))))
      (is (not (> (BigDecimal. "0") (BigDecimal. "0.000"))))
      (is (not (> (BigDecimal. "0.0") (BigDecimal. "0.000"))))
      (is (not (> (BigDecimal. "0.000") (BigDecimal. "0.000"))))

      (is (> 0.001M 0M))
      (is (> 0.001M 0.0M))
      (is (> 0.001M 0.000M))
      (is (> 0.001M BigDecimal/ZERO))
      (is (> 0.001M (BigDecimal. "0")))
      (is (> 0.001M (BigDecimal. "0.0")))
      (is (> 0.001M (BigDecimal. "0.000")))
      (is (> (BigDecimal. "0.001") 0M))
      (is (> (BigDecimal. "0.001") 0.0M))
      (is (> (BigDecimal. "0.001") 0.000M))
      (is (> (BigDecimal. "0.001") BigDecimal/ZERO))
      (is (> (BigDecimal. "0.001") (BigDecimal. "0")))
      (is (> (BigDecimal. "0.001") (BigDecimal. "0.0")))
      (is (> (BigDecimal. "0.001") (BigDecimal. "0.000"))))))
```

### PR DESCRIPTION
**Pull request by jarohen**
Adding support for `BigDecimal`, `LocalDate`, `LocalTime`, `LocalDateTime`, `Instant` and `Duration` as value types, allowing them to be used in range filters.

`BigDecimal` implementation adapted from [Orderly](https://github.com/ndimiduk/orderly/blob/master/orderly-core/src/main/java/orderly/BigDecimalRowKey.java)

RFC: I haven't included `BigInteger` here, because in Clojure there's also `clojure.lang.BigInt` to consider (a separate type to `java.math.BigInteger`, neither being a sub-class/super-class of the other) - this is therefore more susceptible than the others to the known issue of Crux values not being comparable between types, but with (I'd wager) significantly less awareness, even within the Clojure community. Could also be argued that supporting `BigDecimal` but not `BigInteger` is a big gotcha, particularly for JVM devs who _really_ don't care about this Clojure nuance. Eurgh.

Overnight RFC: (definitely a separate PR, if at all) - for the time being, could/should we make range filters refuse to compare values from different types? i.e. `10` is neither `<`, `>` nor `=` to `10.0`? May be less counter-intuitive than having (say) `12.0 < 10` because the binary representation of doubles happen to be 'less' than longs.

### CODE REVIEW

File: crux-core/src/crux/codec.clj [hunk 1]
```diff
@@ -229,6 +240,70 @@
...
+      (if (zero? signum)
+        (-> to (mem/limit-buffer (+ value-type-id-size Byte/BYTES)))
+
+        (let [bcd-len (MathCodec/putBinaryCodedDecimal (str (.abs (.unscaledValue this)))
+                                                       to
+                                                       (+ value-type-id-size Byte/BYTES Integer/BYTES))]
+          (-> to
+              (doto (.putInt (+ value-type-id-size Byte/BYTES)
+                             (MathCodec/encodeExponent this)
+                             java.nio.ByteOrder/BIG_ENDIAN))
```
Comment (hraberg) [inline crux-core/src/crux/codec.clj]: No need for FQN.

File: crux-core/src/crux/codec.clj [hunk 2]
```diff
@@ -229,6 +240,70 @@
...
+              (mem/limit-buffer (+ value-type-id-size Byte/BYTES Integer/BYTES bcd-len)))))))
+
+  LocalDate
+  (value->buffer [this ^MutableDirectBuffer to]
+    (-> to
+        (doto (.putByte 0 localdate-value-type-id))
+        (doto (.putInt value-type-id-size (.getYear this)))
```
Comment (hraberg) [inline crux-core/src/crux/codec.clj]: You want to use the arity taking ByteOrder/BIG_ENDIAN for anything longer than a byte (Char/Short/Int/Long etc.). Applies here and to a few other places in this PR in crux.codec.

File: crux-core/src/crux/codec.clj [hunk 3]
```diff
@@ -292,23 +367,65 @@
...
+      (let [prefix-len (+ value-type-id-size Byte/BYTES Integer/BYTES)
+            decoded-bcd (MathCodec/getBinaryCodedDecimal
+                         (-> buffer
+                             (mem/slice-buffer prefix-len (- (.capacity buffer) prefix-len))))]
+        (MathCodec/decodeBigDecimal signum
+                                    (.getInt buffer (+ value-type-id-size Byte/BYTES) ByteOrder/BIG_ENDIAN)
+                                    decoded-bcd)))))
+
+(defn- decode-localdate [^DirectBuffer buffer]
+  (LocalDate/of (.getInt buffer value-type-id-size)
```
Comment (hraberg) [inline crux-core/src/crux/codec.clj]: As mentioned above, endinaness applies to decode as well.

**Review by hraberg — CHANGES_REQUESTED** [review]
LGTM, few endianess fixes requested. And is assuming the BigDecimal codec is working, haven't read it in detail and verified it :-)

File: crux-core/src/crux/codec.clj (hunk 2 above)
Comment (jarohen) [reply crux-core/src/crux/codec.clj]: oh, yep, cheers :pray:

**Review by hraberg — APPROVED** [review]

**Review by jonpither — APPROVED** [review]
