### PR TITLE
xtdb.arrow fixes around null handling

### LINKED ISSUE #3726: IAE in compactor, nested structure
Error running the compactor - looks like it's not getting aligned types deep into a nested structure

```
13:05:15.784 [xtdb.compactor-3] ERROR xtdb.compactor - Error running compaction job.

java.lang.IllegalArgumentException: Failed requirement.

                at xtdb.arrow.StructVector.rowCopier0(StructVector.kt:101)
                at xtdb.arrow.VectorReader.rowCopier(VectorReader.kt:74)
                at xtdb.arrow.ListVector.rowCopier0(ListVector.kt:90)
                at xtdb.arrow.VectorReader.rowCopier(VectorReader.kt:74)
                at xtdb.arrow.StructVector.rowCopier0(StructVector.kt:103)
                at xtdb.arrow.VectorReader.rowCopier(VectorReader.kt:74)
                at xtdb.arrow.DenseUnionVector$LegWriter.rowCopier0(DenseUnionVector.kt:107)
                at xtdb.arrow.VectorReader.rowCopier(VectorReader.kt:74)
                at xtdb.arrow.DenseUnionVector.rowCopier0(DenseUnionVector.kt:214)
                at xtdb.arrow.DenseUnionVector.rowCopier(DenseUnionVector.kt:226)
                at xtdb.compactor$__GT_reader__GT_copier$reader__GT_copier__30391.invoke(compactor.clj:43)
                at xtdb.compactor$merge_segments_into.invokeStatic(compactor.clj:86)
                at xtdb.compactor$merge_segments_into.invoke(compactor.clj:55)
                at xtdb.compactor$exec_compaction_job_BANG_$fn__30443$fn__30444$fn__30453$fn__30454.invoke(compactor.clj:136)
                at xtdb.compactor$exec_compaction_job_BANG_$fn__30443$fn__30444$fn__30453.invoke(compactor.clj:134)
                at xtdb.compactor$exec_compaction_job_BANG_$fn__30443$fn__30444.invoke(compactor.clj:134)
                at xtdb.compactor$exec_compaction_job_BANG_$fn__30443.invoke(compactor.clj:123)
                at xtdb.compactor$exec_compaction_job_BANG_.invokeStatic(compactor.clj:123)
                at xtdb.compactor$exec_compaction_job_BANG_.invoke(compactor.clj:118)
                at xtdb.compactor$eval30559$fn__30561$compactor_task__30590$fn__30592.invoke(compactor.clj:272)
                at xtdb.compactor$eval30559$fn__30561$compactor_task__30590.invoke(compactor.clj:270)
                at xtdb.compactor$eval30559$fn__30561$fn__30595$fn__30596$fn__30597$fn__30603.invoke(compactor.clj:307)
                at clojure.lang.AFn.run(AFn.java:22)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
                at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)
```

### LINKED ISSUE #3946: `writeNull` on DenseUnionVector fails
Just pasting a stacktrace from @danmason 
```
; 17:22:58.460 [xtdb.compactor-0] ERROR xtdb.compactor - Error running compaction job.
; java.lang.UnsupportedOperationException: writeNull unsupported on DenseUnionVector
; 	at xtdb.arrow.Vectors.unsupported(Vector.kt:26)
; 	at xtdb.arrow.VectorWriter.writeNull(VectorWriter.kt:9)
; 	at xtdb.arrow.StructVector.endStruct(StructVector.kt:62)
; 	at xtdb.arrow.StructVector.rowCopier0$lambda$14(StructVector.kt:108)
; 	at xtdb.arrow.VectorReader.rowCopier$lambda$3(VectorReader.kt:77)
; 	at xtdb.arrow.DenseUnionVector$LegWriter.rowCopier0$lambda$1(DenseUnionVector.kt:108)
; 	at xtdb.arrow.VectorReader.rowCopier$lambda$3(VectorReader.kt:77)
; 	at xtdb.arrow.DenseUnionVector.rowCopier0$lambda$12(DenseUnionVector.kt:218)
; 	at xtdb.arrow.DenseUnionVector.rowCopier$lambda$15$lambda$14(DenseUnionVector.kt:228)
; 	at xtdb.compactor$__GT_reader__GT_copier$reader__GT_copier$reify__24732.copyRow(compactor.clj:52)
; 	at xtdb.compactor$merge_segments_into.invokeStatic(compactor.clj:94)
; 	at xtdb.compactor$merge_segments_into.invoke(compactor.clj:57)
; 	at xtdb.compactor$exec_compaction_job_BANG_$fn__24783$fn__24784$fn__24793$fn__24794.invoke(compactor.clj:138)
; 	at xtdb.compactor$exec_compaction_job_BANG_$fn__24783$fn__24784$fn__24793.invoke(compactor.clj:136)
; 	at xtdb.compactor$exec_compaction_job_BANG_$fn__24783$fn__24784.invoke(compactor.clj:136)
; 	at xtdb.compactor$exec_compaction_job_BANG_$fn__24783.invoke(compactor.clj:125)
; 	at xtdb.compactor$exec_compaction_job_BANG_.invokeStatic(compactor.clj:125)
; 	at xtdb.compactor$exec_compaction_job_BANG_.invoke(compactor.clj:120)
; 	at xtdb.compactor$open_compactor$compactor_task__24946$fn__24948.invoke(compactor.clj:284)
; 	at xtdb.compactor$open_compactor$compactor_task__24946.invoke(compactor.clj:282)
; 	at xtdb.compactor$open_compactor$fn__24951$fn__24952$fn__24953$fn__24959.invoke(compactor.clj:319)
; 	at clojure.lang.AFn.run(AFn.java:22)
; 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
; 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
; 	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
```

### PR DESCRIPTION
**Pull request by FiV0**
The first fix handles copying from the `NullVector` into various other vectors. 
- This mostly means creating a special copier when the source is a `NullVector` in `VectorReader`.
- It also tries to find a suitable vector to write to (a nullable one) in a DUV.

The second fix is a bit controversial as I am adding `writeNull` to the DUV, which also tries to find a suitable leg to write the null. As in other cases this fails with a `TODO` if no suitable vector is found.

I did not touch auto promotion for DUVs. So whenever the target vector can't hold the `nulls` this still fails. Although I am not sure we should ever need that.

### CODE REVIEW

File: core/src/main/kotlin/xtdb/arrow/DenseUnionVector.kt [hunk 1]
```diff
@@ -138,6 +138,20 @@ class DenseUnionVector(
...
+            if (leg.nullable) {
+                legWriter = LegWriter(i.toByte(), leg)
+                break
+            }
+        }
+        legWriter?.writeNull() ?: run {
+            TODO("auto-creation: null vs ${legVectors.map { it.name }}")
+        }
+    }
+
```
Comment (FiV0) [inline core/src/main/kotlin/xtdb/arrow/DenseUnionVector.kt]: The controversial bit. If we start with `writeNull`, we should likely also implement the others.
