### PR TITLE
Catch ArithmeticException at EE boundary

### LINKED ISSUE #3569: Long overflow in UPDATE should error gracefully
```
➜  ~ psql -h localhost -p 5432
psql (16.3, server 16)
Type "help" for help.

jdt=> INSERT into foo (_id, val) VALUES (1, 1);
INSERT 0 0
jdt=> UPDATE foo SET val = (9223372036854775807 + 9223372036854775807) WHERE _id = 1;
UPDATE 0
jdt=> SELECT * FROM foo;
 _id | val 
-----+-----
   1 |   1
(1 row)

jdt=> SELECT * FROM _txs;
 _id | committed | error |             tx_time              
-----+-----------+-------+----------------------------------
   0 | t         |       | 2024-08-06 11:09:29.822173+00:00
(1 row)

jdt=> 
```

```
11:09:34 | ERROR xtdb.indexer | error in indexer
java.lang.ArithmeticException: long overflow
        at java.base/java.lang.Math.addExact(Math.java:931)
        at clojure.core$eval34257$fn__34258.invoke(NO_SOURCE_FILE:0)
        at xtdb.expression$$reify__13915.project(expression.clj:1555)
        at xtdb.operator.project.ProjectCursor$reify__20819.accept(project.clj:124)
        at xtdb.operator.rename.RenameCursor$reify__21628.accept(rename.clj:39)
        at xtdb.operator.scan.TrieCursor$fn__19489.invoke(scan.clj:309)
        at xtdb.operator.scan.TrieCursor.tryAdvance(scan.clj:260)
        at xtdb.operator.rename.RenameCursor.tryAdvance(rename.clj:29)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:116)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:116)
        at xtdb.query$wrap_cursor$reify__25716.tryAdvance(query.clj:78)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at xtdb.indexer$query_indexer$eval_query__25954.invoke(indexer.clj:396)
        at xtdb.indexer$wrap_sql_args$fn__25961.invoke(indexer.clj:430)
        at xtdb.indexer$foreach_arg_row.invokeStatic(indexer.clj:413)
        at xtdb.indexer$foreach_arg_row.invokePrim(indexer.clj)
        at xtdb.indexer$$reify__25966.indexOp(indexer.clj:401)
        at xtdb.indexer.Indexer$fn__26016$index_tx_ops__26019$fn__26032.invoke(indexer.clj:623)
        at clojure.lang.AFn.call(AFn.java:18)
        at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
        at xtdb.indexer.Indexer$fn__26016$index_tx_ops__26019.invoke(indexer.clj:620)
        at xtdb.indexer.Indexer$fn__26016$fn__26040.invoke(indexer.clj:634)
        at xtdb.indexer.Indexer$fn__26016.invoke(indexer.clj:633)
        at xtdb.indexer.Indexer.indexTx(indexer.clj:597)
        at xtdb.log.watcher$watch_log_BANG_$reify__26256.acceptRecord(watcher.clj:53)
        at xtdb.log$tx_handler$fn__17626.invoke(log.clj:37)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at xtdb.log.NotifyingSubscriberHandler$fn__17659.invoke(log.clj:96)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:1583)
11:09:34 | ERROR xtdb.util | Uncaught exception:
java.lang.ArithmeticException: long overflow
        at java.base/java.lang.Math.addExact(Math.java:931)
        at clojure.core$eval34257$fn__34258.invoke(NO_SOURCE_FILE:0)
        at xtdb.expression$$reify__13915.project(expression.clj:1555)
        at xtdb.operator.project.ProjectCursor$reify__20819.accept(project.clj:124)
        at xtdb.operator.rename.RenameCursor$reify__21628.accept(rename.clj:39)
        at xtdb.operator.scan.TrieCursor$fn__19489.invoke(scan.clj:309)
        at xtdb.operator.scan.TrieCursor.tryAdvance(scan.clj:260)
        at xtdb.operator.rename.RenameCursor.tryAdvance(rename.clj:29)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:116)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:116)
        at xtdb.query$wrap_cursor$reify__25716.tryAdvance(query.clj:78)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at xtdb.indexer$query_indexer$eval_query__25954.invoke(indexer.clj:396)
        at xtdb.indexer$wrap_sql_args$fn__25961.invoke(indexer.clj:430)
        at xtdb.indexer$foreach_arg_row.invokeStatic(indexer.clj:413)
        at xtdb.indexer$foreach_arg_row.invokePrim(indexer.clj)
        at xtdb.indexer$$reify__25966.indexOp(indexer.clj:401)
        at xtdb.indexer.Indexer$fn__26016$index_tx_ops__26019$fn__26032.invoke(indexer.clj:623)
        at clojure.lang.AFn.call(AFn.java:18)
        at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
        at xtdb.indexer.Indexer$fn__26016$index_tx_ops__26019.invoke(indexer.clj:620)
        at xtdb.indexer.Indexer$fn__26016$fn__26040.invoke(indexer.clj:634)
        at xtdb.indexer.Indexer$fn__26016.invoke(indexer.clj:633)
        at xtdb.indexer.Indexer.indexTx(indexer.clj:597)
        at xtdb.log.watcher$watch_log_BANG_$reify__26256.acceptRecord(watcher.clj:53)
        at xtdb.log$tx_handler$fn__17626.invoke(log.clj:37)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at xtdb.log.NotifyingSubscriberHandler$fn__17659.invoke(log.clj:96)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:1583)
11:09:34 | DEBUG xtdb.pgwire | Error on execute-tx
java.util.concurrent.ExecutionException: clojure.lang.ExceptionInfo: Ingestion stopped: long overflow {}
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at clojure.core$deref_future.invokeStatic(core.clj:2317)
        at clojure.core$deref.invokeStatic(core.clj:2337)
        at clojure.core$deref.invoke(core.clj:2323)
        at xtdb.indexer.Indexer.awaitTx(indexer.clj:568)
        at xtdb.node.impl.Node.prepareQuery(impl.clj:133)
        at xtdb.node.impl.Node.open_sql_query(impl.clj:115)
        at xtdb.node.impl.Node.execute_tx(impl.clj:105)
        at xtdb.api$execute_tx.invokeStatic(api.clj:208)
        at xtdb.api$execute_tx.invoke(api.clj:180)
        at xtdb.pgwire$execute_tx.invokeStatic(pgwire.clj:1077)
        at xtdb.pgwire$execute_tx.invoke(pgwire.clj:1072)
        at xtdb.pgwire$cmd_exec_dml.invokeStatic(pgwire.clj:1109)
        at xtdb.pgwire$cmd_exec_dml.invoke(pgwire.clj:1095)
        at xtdb.pgwire$cmd_execute.invokeStatic(pgwire.clj:1437)
        at xtdb.pgwire$cmd_execute.invoke(pgwire.clj:1418)
        at xtdb.pgwire$cmd_simple_query.invokeStatic(pgwire.clj:1467)
        at xtdb.pgwire$cmd_simple_query.invoke(pgwire.clj:1442)
        at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1494)
        at xtdb.pgwire$handle_msg.invoke(pgwire.clj:1475)
        at xtdb.pgwire$conn_loop.invokeStatic(pgwire.clj:1561)
        at xtdb.pgwire$conn_loop.invoke(pgwire.clj:1514)
        at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1597)
        at xtdb.pgwire$connect.invoke(pgwire.clj:1564)
        at xtdb.pgwire$accept_loop$fn__34137$fn__34138$fn__34139.invoke(pgwire.clj:1652)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: clojure.lang.ExceptionInfo: Ingestion stopped: long overflow
        at xtdb.await$__GT_ingester_ex.invokeStatic(await.clj:18)
        at xtdb.await$__GT_ingester_ex.invoke(await.clj:17)
        at xtdb.await$notify_ex.invokeStatic(await.clj:60)
        at xtdb.await$notify_ex.invoke(await.clj:56)
        at xtdb.indexer.Indexer.indexTx(indexer.clj:665)
        at xtdb.log.watcher$watch_log_BANG_$reify__26256.acceptRecord(watcher.clj:53)
        at xtdb.log$tx_handler$fn__17626.invoke(log.clj:37)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at xtdb.log.NotifyingSubscriberHandler$fn__17659.invoke(log.clj:96)
        at clojure.lang.AFn.run(AFn.java:22)
        ... 1 common frames omitted
Caused by: java.lang.ArithmeticException: long overflow
        at java.base/java.lang.Math.addExact(Math.java:931)
        at clojure.core$eval34257$fn__34258.invoke(NO_SOURCE_FILE:0)
        at xtdb.expression$$reify__13915.project(expression.clj:1555)
        at xtdb.operator.project.ProjectCursor$reify__20819.accept(project.clj:124)
        at xtdb.operator.rename.RenameCursor$reify__21628.accept(rename.clj:39)
        at xtdb.operator.scan.TrieCursor$fn__19489.invoke(scan.clj:309)
        at xtdb.operator.scan.TrieCursor.tryAdvance(scan.clj:260)
        at xtdb.operator.rename.RenameCursor.tryAdvance(rename.clj:29)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:116)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:116)
        at xtdb.query$wrap_cursor$reify__25716.tryAdvance(query.clj:78)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at xtdb.indexer$query_indexer$eval_query__25954.invoke(indexer.clj:396)
        at xtdb.indexer$wrap_sql_args$fn__25961.invoke(indexer.clj:430)
        at xtdb.indexer$foreach_arg_row.invokeStatic(indexer.clj:413)
        at xtdb.indexer$foreach_arg_row.invokePrim(indexer.clj)
        at xtdb.indexer$$reify__25966.indexOp(indexer.clj:401)
        at xtdb.indexer.Indexer$fn__26016$index_tx_ops__26019$fn__26032.invoke(indexer.clj:623)
        at clojure.lang.AFn.call(AFn.java:18)
        at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
        at xtdb.indexer.Indexer$fn__26016$index_tx_ops__26019.invoke(indexer.clj:620)
        at xtdb.indexer.Indexer$fn__26016$fn__26040.invoke(indexer.clj:634)
        at xtdb.indexer.Indexer$fn__26016.invoke(indexer.clj:633)
        at xtdb.indexer.Indexer.indexTx(indexer.clj:597)
        ... 11 common frames omitted
```

### PR DESCRIPTION
**Pull request by FiV0**
This catches `ArithmeticException`s at the Expression Engine boundary and turns them into runtime exceptions so that we don't fall over in the indexer.

### CODE REVIEW

File: core/src/main/clojure/xtdb/expression.clj [hunk 1]
```diff
@@ -1611,6 +1606,20 @@
   (fn [expr opts]
     (f expr (assoc opts :zone-id (.getZone *clock*)))))
 
+(defn arithmetic-ex->runtime-ex [^Throwable cause]
+  (let [message (.getMessage cause)]
+    (prn message)
```
Comment (jarohen) [inline core/src/main/clojure/xtdb/expression.clj]: cheeky prn

File: core/src/main/clojure/xtdb/expression.clj [hunk 2]
```diff
@@ -1630,9 +1639,11 @@
                                           ~@writer-bindings
                                           row-count# (.getRowCount ~rel-sym)]
                                       (dotimes [~idx-sym row-count#]
-                                        ~(continue (fn [t c]
-                                                     (write-value-out! t c))))))
-
+                                        (try
+                                          ~(continue (fn [t c]
+                                                       (write-value-out! t c)))
+                                          (catch ArithmeticException e#
```
Comment (jarohen) [inline core/src/main/clojure/xtdb/expression.clj]: probably needn't include this in the code generation - just outside should suffice?

**Review by jarohen — CHANGES_REQUESTED** [review]

**Comment by FiV0** [comment]
@jarohen I added another commit for non fitting decimals. Maybe you can have look if the catching at that level seems suspicious.

File: core/src/main/clojure/xtdb/expression.clj [hunk 3]
```diff
@@ -1675,7 +1682,10 @@
             (doto out-vec
               (.setInitialCapacity row-count)
               (.allocateNew))
-            (@!projection-fn in-rel schema params out-vec)
+            (try
+              (@!projection-fn in-rel schema params out-vec)
+              (catch ArithmeticException e#
```
Comment (jarohen) [inline core/src/main/clojure/xtdb/expression.clj]: don't need the gensym here now you're out of macro-land

**Review by jarohen — APPROVED** [review]
