### PR TITLE
Auctionmark automation

### LINKED ISSUE #2771: Get Auctionmark working end-to-end.
Currently the Auctionmark Benchmark mainly fails because of stability issues. Let's try to fix them and get a fully Auctionmark run working.

### PR DESCRIPTION
**Pull request by FiV0**
This PR adds a script and a couple of gradle tasks that should help creating an Auctionmark report more easily.
Being in the `modules/bench` directory, one should (big  emphasis on "should") now be able to create a comparison report with just one command.
```
./bin/auctionmark-compare.clj --load-phase false --duration "PT30S"
```

TODO:
- [x] some small issues with the gradle task to be sorted out

### CODE REVIEW

File: modules/bench/src/main/clojure/xtdb/bench2/xtdb2.clj [hunk 1]
```diff
@@ -192,6 +194,49 @@
...
+    (let [report (-> (run-benchmark
+                      {:node-opts {:node-dir node-dir
+                                   :instant-src InstantSource/SYSTEM}
+                       :benchmark-type :auctionmark
+                       :benchmark-opts (assoc opts :sync true)})
+                     only-oltp-stage)]
+      (spit (io/file output-file) report))))
+
+(def cli-options
+  [[nil "--load-phase LOAD-PHASE" :parse-fn #(if (or (= % "false") (= % "nil")) false true)]
```
Comment (jarohen) [inline modules/bench/src/main/clojure/xtdb/bench2/xtdb2.clj]: nit: `(if p false true)` => `#(not (or (= % "false") (= % "nil")))`

File: modules/bench/src/main/clojure/xtdb/bench2/xtdb2.clj [hunk 2]
```diff
@@ -192,6 +194,49 @@
...
+   [nil "--output-file OUTPUT-FILE"]
+   [nil "--node-dir NODE-DIR"]
+   [nil "--duration DURATION" :validate [(fn [x] (try (Duration/parse x)
```
Comment (jarohen) [inline modules/bench/src/main/clojure/xtdb/bench2/xtdb2.clj]: I'd have guessed that throwing an error from `:parse-fn #(Duration/parse %)` would do the same thing?

File: modules/bench/src/main/clojure/xtdb/bench2/xtdb2.clj [hunk 3]
```diff
@@ -192,6 +194,49 @@
...
+                                                      (catch Throwable _t
+                                                        false)
+                                                      (finally true)))
```
Comment (jarohen) [inline modules/bench/src/main/clojure/xtdb/bench2/xtdb2.clj]: can't return anything from `finally`

File: modules/bench/src/main/clojure/xtdb/bench2/xtdb2.clj [hunk 4]
```diff
@@ -192,6 +194,49 @@
...
+                                         "Incorrect duration period"]]
+   [nil "--threads THREADS" :parse-fn #(Long/parseLong %)]
+   [nil "--scale-factor" :parse-fn #(Double/parseDouble %)]])
+
+(defn -main [& args]
+  (let [{:keys [options _arguments errors]} (cli/parse-opts args cli-options)]
+    (prn options)
```
Comment (jarohen) [inline modules/bench/src/main/clojure/xtdb/bench2/xtdb2.clj]: cheeky prn? if you want this to stick around, worth using `log/...` instead?

File: modules/bench/README.adoc [hunk 5]
```diff
@@ -6,6 +6,14 @@ Auctionmark runs in some capacity currently, this guide describes the requiremen
 - Run AWS_PROFILE=<profile_name_containing_above_creds> bin/download-dataset.sh --auctionmark (skip)
 - See comments at bottom of xtdb.bench2.xtdb.clj for further instructions.
 
+=== Creating a C1 vs C2 comparison report
+
+The following setup assumes that you have `2.x` checked out and another directory at `../xtdb` which can checkout the `auctionmark` branch of C1. Make sure there is nothing to be stashed on your (presumably C1) working branch.
```
Comment (jarohen) [inline modules/bench/README.adoc]: nit: with AsciiDoc, the [best practice](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line) is one sentence per line.

File: modules/bench/README.adoc [hunk 6]
```diff
@@ -6,6 +6,14 @@ Auctionmark runs in some capacity currently, this guide describes the requiremen
...
+The following scrip twill first run a C1 auctionmark on your machine followed by a C2 run and finally creates a report for comparison. It assumes you are placed at the root of the `modules/bench` directory.
```
Comment (jarohen) [inline modules/bench/README.adoc]: thai-po - `scrip twill`

File: build.gradle.kts [hunk 7]
```diff
@@ -210,6 +210,24 @@ if (hasProperty("fin")) {
     }
 }
 
+tasks.create("run-auctionmark", JavaExec::class) {
```
Comment (jarohen) [inline build.gradle.kts:222]: I'd likely stick this in the bench module `build.gradle.kts`, which I think would save you a little bit of the faffery here and in your bb script around current directories etc?

You can still call it from the root should we wish, just with `./gradlew modules:bench:run-auctionmark` instead

File: build.gradle.kts [hunk 8]
```diff
@@ -233,43 +251,43 @@ fun createSltTask(
...
-        maxErrors = if (project.hasProperty("testMaxErrors")) {
-            val testMaxErrors: String by project
-            if (testMaxErrors.isEmpty()) { 0 } else { testMaxErrors.toLong() }
-        } else { 0 },
-        testFiles = if (project.hasProperty("testDir")) {
-            val testDir: String by project
-            listOf(testDir)
-        } else { emptyList() },
-        extraArgs = listOf("--dirs"))
+ createSltTask(
```
Comment (jarohen) [inline build.gradle.kts]: mind reverting this indentation diff if it wasn't intentional/related? makes the PR easier to check :slightly_smiling_face:

File: modules/bench/bin/auctionmark-compare.clj [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+(def debug true)
+
+(def cli-opts {:coerce {:load-phase :boolean :duration :string}})
+(def opts (cli/parse-opts *command-line-args* cli-opts))
+
+(def c1-auctionmark-file "/tmp/auctionmark-c1-run.edn")
+(def c2-auctionmark-file "/tmp/auctionmark-c2-run.edn")
+(def jvm-args ["-Xmx2g", "-Xms2g", "-XX:MaxDirectMemorySize=3g", "-XX:MaxMetaspaceSize=1g"])
+
+(when debug (prn opts))
```
Comment (jarohen) [inline modules/bench/bin/auctionmark-compare.clj]: is this the idiomatic way to check the logging level on bb? I've not used it a lot, but I'd guess they'd have something similar to c.t.logging?

**Review by jarohen — CHANGES_REQUESTED** [review]
Hey @FiV0, quick notes below. I've shunted this back to draft/in progress for now because of the outstanding todo on the PR description?

File: modules/bench/bin/auctionmark-compare.clj (hunk 9 above)
Comment (FiV0) [reply modules/bench/bin/auctionmark-compare.clj]: I can add normal logging. I just thought as this is some hacky script it doesn't matter much.

File: build.gradle.kts (hunk 7 above)
Comment (FiV0) [reply build.gradle.kts:222]: Should I then add a `./gradlew` script to the `modules/bench` directory or just invoke as you describe? That would still be from the root directory then.
