### PR TITLE
Eager watermarks

### LINKED ISSUE #3315: `splitAndTransfer` (aka opening a watermark) while a buffer is being reallocated causes an error
It seems to happen that opening a Watermark in on the live index throws, as the underlying vectors get either closed or realloacted.
```
14:16:27.517 [core2-benchmark-pool-16-thread-4] ERROR xtdb.bench - Error while executing xtdb.bench.auctionmark$proc_get_item@4daa4792
java.lang.IllegalArgumentException: Invalid parameters startIndex: 0, length: 17991 for valueCount: 0
	at org.apache.arrow.util.Preconditions.checkArgument(Preconditions.java:413)
	at org.apache.arrow.vector.BaseFixedWidthVector.splitAndTransferTo(BaseFixedWidthVector.java:635)
	at org.apache.arrow.vector.BigIntVector$TransferImpl.splitAndTransfer(BigIntVector.java:360)
	at org.apache.arrow.vector.complex.NonNullableStructVector$StructTransferPair.splitAndTransfer(NonNullableStructVector.java:338)
	at org.apache.arrow.vector.complex.StructVector$NullableStructTransferPair.splitAndTransfer(StructVector.java:293)
	at org.apache.arrow.vector.complex.DenseUnionVector$TransferImpl.splitAndTransfer(DenseUnionVector.java:1192)
	at xtdb.util$slice_vec.invokeStatic(util.clj:353)
	at xtdb.util$slice_vec.invokePrim(util.clj)
	at xtdb.util$slice_vec.invokeStatic(util.clj:333)
	at xtdb.util$slice_vec.invokePrim(util.clj)
	at xtdb.util$slice_vec.invokeStatic(util.clj:332)
	at xtdb.util$slice_vec.invoke(util.clj:331)
	at xtdb.indexer.live_index$open_wm_live_rel.invokeStatic(live_index.clj:87)
	at xtdb.indexer.live_index$open_wm_live_rel.invoke(live_index.clj:81)
	at xtdb.indexer.live_index.LiveTable.openWatermark(live_index.clj:195)
	at xtdb.indexer.live_index.LiveIndex$open_live_idx_wm__76777.invoke(live_index.clj:329)
	at xtdb.indexer.live_index.LiveIndex.openWatermark(live_index.clj:355)
	at xtdb.indexer.Indexer.openWatermark(indexer.clj:657)
	at xtdb.operator.scan$tables_with_cols.invokeStatic(scan.clj:119)
	at xtdb.operator.scan$tables_with_cols.invoke(scan.clj:116)
	at xtdb.node.impl.Node$fn__100267.invoke(impl.clj:92)
	at xtdb.util$$reify__62690.apply(util.clj:291)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

### PR DESCRIPTION
**Pull request by FiV0**
This PR adds eager watermarks which are taken on commit in the indexing thread. The `tx-key` on `openWatermark` is pointless now as it was previously only used to check if an existing watermark was able to satisfy the `tx-key`. The waiting on the correct tx-key is still the callers responsibility.

This should also fix #3315.

I checked against Auctionmark a couldn't see any significant slow down:
Selection_028

Left with eager Watermark , right as previously (with one failure thread as per #3315).

TPC-H ingest of ScaleFactor 0.3 took
- 52secs on `main`
- 55secs on this

Todo:
- [x] remove `tx-key` from `openWatermark`

### CODE REVIEW

File: core/src/main/clojure/xtdb/indexer/live_index.clj [hunk 1]
```diff
@@ -92,6 +92,22 @@
         (when retain? (util/close out-cols))
         (throw t)))))
 
+(defn live-table-wm [^IRelationWriter live-rel, trie, retain?]
+  (let [fields (live-rel->fields live-rel)
+        wm-live-rel (open-wm-live-rel live-rel retain?)
+        wm-live-trie (cond-> ^LiveHashTrie trie
+                       retain? (.withIidReader (.readerForName wm-live-rel "xt$iid")))]
```
Comment (FiV0) [inline core/src/main/clojure/xtdb/indexer/live_index.clj:99]: @mbutlerw did it like this now. You see any issues with this when retain is false and it's being called non inside a transaction?

**Review by mbutlerw — APPROVED** [review]

**Review by jarohen — APPROVED** [review]
