### PR TITLE
Fix LeafMergeQueue for non-consecutive ordinals

### LINKED ISSUE #2714: Fix `LeafMergeQueue` when ordinals are not consecutive

### PR DESCRIPTION
**Pull request by FiV0**
A leaf merge task might contain ordinals (the log tries participating in the merge task)  that are not consecutive. Say for example log-tries with ordinals 1 and 3 are participating in the merge task. This would create issues with the indexing into the readers in the `LeafMergeQueue`. This PR addresses that.

### CODE REVIEW

File: core/src/main/java/xtdb/trie/LeafMergeQueue.java [hunk 1]
```diff
@@ -35,31 +36,44 @@ public String toString() {
 
     private final byte[] path;
     private final IVectorReader[] rdrs;
+    private final HashMap<Integer, Integer> ordinalToIndex;
     private final PriorityQueue<LeafPointer> pq;
```
Comment (FiV0) [inline core/src/main/java/xtdb/trie/LeafMergeQueue.java]: Realized during Standup that we could also just maintain a map from <ordinal, ivectorreader> and that that is probably simpler.

Comment (FiV0) [reply core/src/main/java/xtdb/trie/LeafMergeQueue.java]: Addressed.

**Review by jarohen — CHANGES_REQUESTED** [review]
Nice one @FiV0, good spot 👏

We probably don't want to be doing map lookups here if we can avoid it - would a sparse array work instead?

**Comment by FiV0** [comment]
@jarohen which of the two map lookups? I am assuming the Clojure one.
