### PR TITLE
Dealing with `erase` in the compactor - #4017

### LINKED ISSUE #4017: Null pointer exception in compactor
The compactor crashes with:
```
14:21:54 | ERROR xtdb.compactor | Error running compaction job.
java.lang.NullPointerException: Cannot invoke "xtdb.bitemporal.IPolygonReader.getRecency()" because the return value of "clojure.lang.IFn.invoke(Object)" is null
        at xtdb.compactor$merge_segments_into.invokeStatic(compactor.clj:97)
        at xtdb.compactor$merge_segments_into.invoke(compactor.clj:57)
        at xtdb.compactor$exec_compaction_job_BANG_$fn__19650$fn__19651$fn__19660$fn__19661.invoke(compactor.clj:138)
        at xtdb.compactor$exec_compaction_job_BANG_$fn__19650$fn__19651$fn__19660.invoke(compactor.clj:136)
        at xtdb.compactor$exec_compaction_job_BANG_$fn__19650$fn__19651.invoke(compactor.clj:136)
        at xtdb.compactor$exec_compaction_job_BANG_$fn__19650.invoke(compactor.clj:125)
        at xtdb.compactor$exec_compaction_job_BANG_.invokeStatic(compactor.clj:125)
        at xtdb.compactor$exec_compaction_job_BANG_.invoke(compactor.clj:120)
        at xtdb.compactor$open_compactor$compactor_task__19813$fn__19815.invoke(compactor.clj:284)
        at xtdb.compactor$open_compactor$compactor_task__19813.invoke(compactor.clj:282)
        at xtdb.compactor$open_compactor$fn__19818$fn__19819$fn__19820$fn__19826.invoke(compactor.clj:319)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
```

I was able to replicate it using a dump of the volume and the following commands:

```console
$ mkdir -p /tmp/npe-test
$ tar -xvf xtdb.tar -C /tmp/npe-test
$ docker run -it --pull=always -p 6543:3000 -p 5432:5432 -v "/tmp/npe-test/_data:/var/lib/xtdb" ghcr.io/xtdb/xtdb:latest
```

I'll link the dump in slack

### PR DESCRIPTION
**Pull request by FiV0**
I am stopping copying compaction history when an `erase` event is encountered for a given `iid`. This also means history before the `erase` will not show up in the L files of the current level and in higher levels. 

~I am also writing `-1` as recency as I couldn't think of any value that made sense for recency in the context of `erase`. We should (in theory) never look at this value.~ We can likely set recency to `system-time` but we are playing it save by setting it to `end of time` (for now).

### CODE REVIEW

File: core/src/main/clojure/xtdb/compactor.clj [hunk 1]
```diff
@@ -89,17 +89,24 @@
...
+                                          (.copyRow row-copier (.getIndex ev-ptr))
+                                          (.writeLong recency-wtr (.getRecency ^IPolygonReader polygon))
+                                          true)
+
+                                        (do
+                                          ;; the first time we encounter an erase
+                                          (when previous-polygon?
+                                            (.copyRow row-copier (.getIndex ev-ptr))
+                                            (.writeLong recency-wtr -1))
+                                          false))]
```
Comment (FiV0) [inline core/src/main/clojure/xtdb/compactor.clj]: A bit of weird one. I could also check the `event-ptr` explicitly for `erase` if you think that is more readable.

File: core/src/main/clojure/xtdb/compactor.clj [hunk 2]
```diff
@@ -89,17 +89,24 @@
...
+                                        (do
+                                          (.copyRow row-copier (.getIndex ev-ptr))
+                                          (.writeLong recency-wtr (.getRecency ^IPolygonReader polygon))
+                                          true)
+
+                                        (do
+                                          ;; the first time we encounter an erase
+                                          (when previous-polygon?
+                                            (.copyRow row-copier (.getIndex ev-ptr))
+                                            (.writeLong recency-wtr -1))
```
Comment (jarohen) [inline core/src/main/clojure/xtdb/compactor.clj]: set to long/max with note that we think we might be able to set it to the system-time of the erase event, but we'd rather play it safe.

File: core/src/main/clojure/xtdb/compactor.clj [hunk 3]
```diff
@@ -89,17 +89,24 @@
         (when (.isValid ev-ptr is-valid-ptr path)
           (.add merge-q {:ev-ptr ev-ptr, :row-copier row-copier})))
 
-      (loop []
+      (loop [previous-polygon? false]
```
Comment (jarohen) [inline core/src/main/clojure/xtdb/compactor.clj]: nit: naming - `seen-erase?`?

File: src/test/clojure/xtdb/compactor_test.clj [hunk 4]
```diff
@@ -481,3 +481,37 @@
...
+                 (xt/q node "SELECT _id FROM foo FOR ALL VALID_TIME FOR ALL SYSTEM_TIME")))
+
+        (xt/submit-tx node [[:put-docs :foo {:xt/id id}]])
+        (tu/finish-chunk! node)
+        (c/compact-all! node #xt/duration "PT0.5S")
+
+        (t/is (= [{:xt/id id-before} {:xt/id id} {:xt/id id-after} ]
+                 (xt/q node "SELECT _id FROM foo FOR ALL VALID_TIME FOR ALL SYSTEM_TIME"))))
+
+      ;; an id where there is no data shouldn't show up in the compacted files
```
Comment (jarohen) [inline src/test/clojure/xtdb/compactor_test.clj]: nit: `t/testing`

**Review by jarohen — APPROVED** [review]
